global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'monitoring-web'
    static_configs:
      - targets: ['web:8000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'monitoring-postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'monitoring-rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
  
  - job_name: 'monitoring-redis'
    static_configs:
      - targets: ['redis-exporter:9121']